CC = g++
CPPFLAGS = -O3 -std=c++11
obj = eax.h individual.h node.h parameter.h tour.h
TSP: main.cpp eax.h individual.h node.h parameter.h tour.h
	$(CC) main.cpp $(obj) $(CPPFLAGS) -o TSP
clean: 
	rm TSP
